### ISSUE TITLE
Keyboard disappears after each character entered when editing

### ISSUE THREAD

**Issue by Markoise** [lneugebauer/nextcloud-cookbook#110] opened 2024-11-10 11:46 UTC
**Describe the bug**
If you want to edit a recipe, the keyboard disappears every time you enter a character. You then have to type again in the field to be edited to enter the next character.

**To Reproduce**
1. open recipe
2. press the edit button
3. Tap the field to be edited
4. change or add characters
5. after the first character tapped on the keyboard, the keyboard disappears.
6. everything is repeated from point 3 onwards

**Expected behavior**
The keyboard remains open during editing.

**Screenshots**

**Smartphone:**

 - Device: Pixel 7
 - OS: Android 15

**Comment by lneugebauer** [comment] 2024-11-10 12:01
Duplicate of #108

**Closed by lneugebauer** 2024-11-10 12:01 UTC
Labels: bug
