### ISSUE TITLE
Crash of the App when selecting a category

### ISSUE THREAD

**Issue by rtglobal** [lneugebauer/nextcloud-cookbook#44] opened 2023-09-23 07:17 UTC
**Describe the bug**

I use your Android-App for a look into my nextcloud recipes. If I choose the middle bottom button for a list of my categories and I click on a category with more than one recipies inside, the app crashes.

**To Reproduce**

**Expected behavior**

I would have shown a list of my recipes related to the choosen category.

**Screenshots**

**Smartphone:**

 - Device: [e.g. Pixel 7]
 - OS: [e.g. Android 13]
Device: Redmi Note 11S
OS: MIUI 14.0.3

**Additional context**

I have a category with only one related recipe. If I choose this category the related recipe will be shown. No app crash.

**Comment by lneugebauer** [comment] 2023-09-25 19:52
Hi @rtglobal, thank you for reporting this issue. I may already have solved this issue with e1d4724. I'll try to create a new release tomorrow.

**Comment by lneugebauer** [comment] 2023-09-30 06:46
Hi @rtglobal, can you confirm the issue is fixed with the lastest release v0.13.0?

**Comment by rtglobal** [comment] 2023-10-01 20:28
Yes, I can confirm this. Wonderful work. I like the new look. Thank you in advance.

**Closed** 2023-10-01 20:30 UTC
Labels: bug
