### ISSUE TITLE
Difficult insert test on the field Ingredients 

### ISSUE THREAD

**Issue by lampgnu** [lneugebauer/nextcloud-cookbook#114] opened 2024-11-15 12:00 UTC
**Describe the bug**
When add a text on the ingredients field the keyboard disappears, with each letter I add

**To Reproduce**
1. Create a new recipe
2. Add new ingredients field
3. Add text in the ingredients field

**Expected behavior**
I expect that I can add text as all field without that disappear the keyboard. 

https://github.com/user-attachments/assets/808b98a0-f3de-4102-a2fb-d361fc9cd770

**Comment by lneugebauer** [comment] 2024-11-15 12:14
Duplicate oft #108

**Closed** 2024-11-15 12:14 UTC
Labels: bug
