### ISSUE TITLE
Crash after the first logon. | Pixel 6 / Android 13

### ISSUE THREAD

**Issue by Mega349** [lneugebauer/nextcloud-cookbook#31] opened 2023-07-04 08:22 UTC
**Describe the bug**
Crash after the first logon.

**To Reproduce**
1. Start app
2. Logon to NC
3. Crash
4. Restart app
5. Crash
6. ...

**Smartphone:**
 - Device: Pixel 6
 - OS: Android 13

**Server:**
- Nextcloud: 26.0.3
- Cookbook:  0.10.2

**Comment by lneugebauer** [comment] 2023-07-04 09:35
Hej @Mega349, thank you for your bug report.

Since I can not reproduce this issue with my cloud, can you give me some more insight about your hosting environment?

Did you use the Nextcould AIO project, web installer on some shared hosting platform, ...?

Is your cloud publicly available or do you host at home/behind a firewall?

**Comment by Mega349** [comment] 2023-07-04 09:36
Dockerized installation with a Nginx Reverse proxy for public access

**Comment by Mega349** [comment] 2023-07-04 09:40
This is the only log msg i got from my cloud (apache):
`"GET /ocs/v2.php/cloud/capabilities?format=json HTTP/1.1" 200 3271 "-" "okhttp/4.11.0`

**Comment by lneugebauer** [comment] 2023-07-04 18:27
Hmm, as this is the only log message you can find, I suspect this issue is fixed by 57f261cfdc714366504d111f46e75d59fb145c24. I've uploaded a new build to Google Play and am waiting for it to be reviewed.

I'll contact you when the update is live.

If the update doesn't fix the problem, you can read your phone's logs using Logcat [CLI](https://developer.android.com/tools/logcat) or [Android Studio](https://developer.android.com/studio/debug/logcat).

But let's wait for the update first.

**Comment by Mega349** [comment] 2023-07-04 20:01
Still crashing with the dev build...
But i dont had a "keystore.properties" file when compiling, is this necessary?

**Comment by lneugebauer** [comment] 2023-07-04 20:17
I can give you more detailed information about the dev build tomorrow when I'm back at my desk.

I was able to crash the app while trying to login. Can you tell me whether you used the normal or manual login?

When using the normal login, I wasn't able to reproduce your issue. But using the manual login I now am able to reproduce the (or at least some) issue and can take a deeper look at it tomorrow!

**Comment by Mega349** [comment] 2023-07-05 06:47
I tried both, normal and manual.

**Comment by lneugebauer** [comment] 2023-07-05 18:02
@Mega349, I assume that you have Android Studio installed, as you wrote you were able to compile and install the debug build.

You don't actually need the `keystore.properties` file. I'll update the README to reflect this change.

Once the app has been built, it should be installed on your emulator (or device, if you enabled developer mode and connected it) and you should be able to see the login screen.

Once the app has started, you can open Logcat (at the bottom of Android Studio) and see all logs of your device. If this is the case, you can continue to login and see the error message. The one I was able to reproduce looks like this.

```
2023-07-05 19:44:42.263  3224-5176  okhttp.OkHttpClient     de....bauer.nextcloudcookbook.debug  I  <-- 200 https://example.com/ocs/v2.php/cloud/capabilities?format=json (2031ms, unknown-length body)
2023-07-05 19:44:42.282  3224-3224  AndroidRuntime          de....bauer.nextcloudcookbook.debug  E  FATAL EXCEPTION: main
                                                                                                    Process: de.lukasneugebauer.nextcloudcookbook.debug, PID: 3224
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'de.lukasneugebauer.nextcloudcookbook.core.domain.model.UserStatus de.lukasneugebauer.nextcloudcookbook.core.data.dto.UserStatusDto.toUserStatus()' on a null object reference
                                                                                                    	at de.lukasneugebauer.nextcloudcookbook.core.data.dto.CapabilitiesDto.toCapabilities(CapabilitiesDto.kt:14)
                                                                                                    	at de.lukasneugebauer.nextcloudcookbook.core.data.repository.AccountRepositoryImpl$getCapabilities$2.invokeSuspend(AccountRepositoryImpl.kt:34)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@15a0d0b, Dispatchers.Main.immediate]
```

Please provide the error message thrown by your device. This will help me to identify out the issue you are experiencing.

In the meantime, I'll already take a look at the issue I was able to create.

**Comment by Mega349** [comment] 2023-07-06 19:58
```log
2023-07-06 21:56:14.499 25125-25125 dcookbook.debug         de....bauer.nextcloudcookbook.debug  W  Attempt to remove non-JNI local reference, dumping thread
2023-07-06 21:56:14.501 25125-25125 AndroidRuntime          de....bauer.nextcloudcookbook.debug  E  FATAL EXCEPTION: main
                                                                                                    Process: de.lukasneugebauer.nextcloudcookbook.debug, PID: 25125
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'de.lukasneugebauer.nextcloudcookbook.core.domain.model.UserStatus de.lukasneugebauer.nextcloudcookbook.core.data.dto.UserStatusDto.toUserStatus()' on a null object reference
                                                                                                    	at de.lukasneugebauer.nextcloudcookbook.core.data.dto.CapabilitiesDto.toCapabilities(CapabilitiesDto.kt:14)
                                                                                                    	at de.lukasneugebauer.nextcloudcookbook.core.data.repository.AccountRepositoryImpl$getCapabilities$2.invokeSuspend(AccountRepositoryImpl.kt:34)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b870e3b, Dispatchers.Main.immediate]
2023-07-06 21:56:14.537 25125-25125 Process                 de....bauer.nextcloudcookbook.debug  I  Sending signal. PID: 25125 SIG: 9
```

**Comment by lneugebauer** [comment] 2023-07-07 20:41
Hej @Mega349, could you please checkout the `fix/31-login-crash` branch and see if those changes solve the issue? You may need to clear the app storage or uninstall it first.

**Comment by Mega349** [comment] 2023-07-07 21:24
No crash, but...:
After successfull logon, nothing happend.
I tipped the `X` and i got Auth failed, on the First screen

---

## 1. After entering the cloud URL:
![Screenshot_20230707-230504](https://github.com/lneugebauer/nextcloud-cookbook/assets/36415117/f64fac2f-ba45-457a-872d-0c854fc281ee)
---
## 2. After Successfull Auth:
![Screenshot_20230707-230511](https://github.com/lneugebauer/nextcloud-cookbook/assets/36415117/9ebf57a2-3260-4a22-8604-7b8aeaca1b01)
---
## 3. After tipping at the `X` to continue
![Screenshot_20230707-230524](https://github.com/lneugebauer/nextcloud-cookbook/assets/36415117/20290eae-0234-488b-bbb5-ed5adb33bc3c)

--- 

Back at the first page with an auth error...
Bevor the patch, the app crashed after step 2, with or without `X` to continue, just after a while.

Here, the log from the first URL page while pressing the button login (Anmelden), back to the URL page without success.

(`2023-07-07 23:18:20.160... ...D  Owner FocusChanged(true)` is btw. the only msg after tipping `X`)

Log:
```log
2023-07-07 23:18:10.969 30826-3272  okhttp.OkHttpClient     de....bauer.nextcloudcookbook.debug  I  --> POST https://cloud.hidden.whatever/login/v2 (0-byte body)
2023-07-07 23:18:11.019 30826-3272  TrafficStats            de....bauer.nextcloudcookbook.debug  D  tagSocket(94) with statsTag=0xffffffff, statsUid=-1
2023-07-07 23:18:11.247 30826-3272  okhttp.OkHttpClient     de....bauer.nextcloudcookbook.debug  I  <-- 200 https://cloud.hidden.whatever/login/v2 (277ms, unknown-length body)
2023-07-07 23:18:11.253 30826-30826 LoginViewM...inEndpoint de....bauer.nextcloudcookbook.debug  V  Open web view with url https://cloud.hidden.whatever/login/v2/flow/inRLQ2qsJ46v0oU6sPmJqfl7sb4wemG8sRgZr0pgl6Y2rQpsmCskOBLQrSdkVE9nSSHZWUK6elbMM6xtG4dC98G2tdo8cJymEBPfmhid3bMVg2bI4mzn8U9sdFYV9dFg
2023-07-07 23:18:11.257 30826-3272  okhttp.OkHttpClient     de....bauer.nextcloudcookbook.debug  I  --> POST https://cloud.hidden.whatever/login/v2/poll?token=GRYbGReOSOOlLdYinDES3m06iRWzsGHYrDuFudm2BMcKV8WPEBGYf3Kt61UwYHX5f0wPvwrSR6VkJ8jpm2ZM7mZfJupw88c0cKGjXK5dAB7IYFE06GX7DSOWNO1O4sFW (0-byte body)
2023-07-07 23:18:11.315 30826-3272  okhttp.OkHttpClient     de....bauer.nextcloudcookbook.debug  I  <-- 404 https://cloud.hidden.whatever/login/v2/poll?token=GRYbGReOSOOlLdYinDES3m06iRWzsGHYrDuFudm2BMcKV8WPEBGYf3Kt61UwYHX5f0wPvwrSR6VkJ8jpm2ZM7mZfJupw88c0cKGjXK5dAB7IYFE06GX7DSOWNO1O4sFW (58ms, 2-byte body)
2023-07-07 23:18:11.812 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(0)] "Error with Feature-Policy header: Unrecognized feature: 'payment'.", source:  (0)
2023-07-07 23:18:12.212 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "JQMIGRATE: Migrate is installed, version 3.4.0", source: https://cloud.hidden.whatever/dist/core-common.js?v=19245f16-19 (2)
2023-07-07 23:18:12.247 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:12.249 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:12.250 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:12.252 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "session heartbeat polling started", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:12.258 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:12.258 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:14.448 30826-30826 Compose Focus           de....bauer.nextcloudcookbook.debug  D  Owner FocusChanged(false)
2023-07-07 23:18:14.547 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(0)] "Error with Feature-Policy header: Unrecognized feature: 'payment'.", source:  (0)
2023-07-07 23:18:14.898 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "JQMIGRATE: Migrate is installed, version 3.4.0", source: https://cloud.hidden.whatever/dist/core-common.js?v=19245f16-19 (2)
2023-07-07 23:18:14.927 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:14.927 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:14.932 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "session heartbeat polling started", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:16.150 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(6)] "Uncaught TypeError: wrapper.getElementsByClassName(...).forEach is not a function", source: https://cloud.hidden.whatever/core/js/login/grant.js?v=19245f16-19 (6)
2023-07-07 23:18:16.322 30826-3272  okhttp.OkHttpClient     de....bauer.nextcloudcookbook.debug  I  --> POST https://cloud.hidden.whatever/login/v2/poll?token=GRYbGReOSOOlLdYinDES3m06iRWzsGHYrDuFudm2BMcKV8WPEBGYf3Kt61UwYHX5f0wPvwrSR6VkJ8jpm2ZM7mZfJupw88c0cKGjXK5dAB7IYFE06GX7DSOWNO1O4sFW (0-byte body)
2023-07-07 23:18:16.389 30826-3272  okhttp.OkHttpClient     de....bauer.nextcloudcookbook.debug  I  <-- 404 https://cloud.hidden.whatever/login/v2/poll?token=GRYbGReOSOOlLdYinDES3m06iRWzsGHYrDuFudm2BMcKV8WPEBGYf3Kt61UwYHX5f0wPvwrSR6VkJ8jpm2ZM7mZfJupw88c0cKGjXK5dAB7IYFE06GX7DSOWNO1O4sFW (66ms, 2-byte body)
2023-07-07 23:18:16.962 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(0)] "Error with Feature-Policy header: Unrecognized feature: 'payment'.", source:  (0)
2023-07-07 23:18:17.199 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "JQMIGRATE: Migrate is installed, version 3.4.0", source: https://cloud.hidden.whatever/dist/core-common.js?v=19245f16-19 (2)
2023-07-07 23:18:17.222 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:17.223 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:17.229 30826-30826 chromium                de....bauer.nextcloudcookbook.debug  I  [INFO:CONSOLE(2)] "session heartbeat polling started", source: https://cloud.hidden.whatever/dist/core-main.js?v=19245f16-19 (2)
2023-07-07 23:18:20.160 30826-30826 Compose Focus           de....bauer.nextcloudcookbook.debug  D  Owner FocusChanged(true)
```

**Comment by lneugebauer** [comment] 2023-07-08 09:15
Alright, I found the issue.

The app currently relies on the `User status` app to be enabled. I'll update it so that it no longer relies on it.
In the meantime, if you already want to use my app, you can simply enable the `User status` app in your Nextcloud.

![User status app](https://github.com/lneugebauer/nextcloud-cookbook/assets/25110308/587160e3-fc9e-4276-b12f-9bda0aaa20f5)

Thanks again for reporting the issue! It really helps me improve the app. 😊

After the first public release, I quickly found out that there are a lot of pitfalls with users hosting their own servers ... So many variables to consider. 😀

**Closed** 2023-07-09 08:02 UTC
Labels: bug
