### ISSUE TITLE
App is missing the ingredient calculation feature

### ISSUE THREAD

**Issue by Daniel-MFG** [lneugebauer/nextcloud-cookbook#79] opened 2024-07-03 11:46 UTC
**Is your feature request related to a problem? Please describe.**
One of my favorite features of the web version of the cookbook is that it can automatically calculate how much of the ingredients is needed based on the portions...
That feature seems to be missing here.

**Describe the solution you'd like**
It would be nice to just add it in a similar way as it is  on the web version... 
Maybe with some sort of cache so it remembers your selection in case you closed the app while you were cooking (tho that would be an optional addition i could live without)

**Describe alternatives you've considered**
The only alternative would be to do it by hand which can be cumbersome in some cases...

![Screenshot_20240703-134513](https://github.com/lneugebauer/nextcloud-cookbook/assets/83823789/b6a14ed2-5422-4085-b2bc-92a2c8f1cdd1)

**Comment by lneugebauer** [comment] 2024-07-03 11:58
Duplicate of #62

**Closed by lneugebauer** 2024-07-03 11:58 UTC
Labels: enhancement
